export const SET_USER = "SET_USER";
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_COMMENTS = "GET_COMMENTS";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const EDIT_COMMENT = "EDIT_COMMENT";